spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      server-addr: 121.36.99.140:8848
    gateway:
      routes:
        - id: stock_route
          uri: lb://mall-stock
          predicates:
            - Path=/api/stock/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: goods_route
          uri: lb://mall-goods
          predicates:
            - Path=/api/goods/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: user_route
          uri: lb://mall-user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: oss_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/api/**  #前端请求都携带 /api 前缀
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #路径重写，将/api/(?<segment.*>)重写为/renren-fast/$\{segment}
          #前端请求http://localhost:88/api/captcha.jpg ----> http://localhost:8080/renren-fast/captcha.jpg

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remote_user
    password: 139494tang
    url: jdbc:mysql://150.158.147.6:3306/mall_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  #解决gateway 与 mvc 包冲突的问题
  main:
    web-application-type: reactive

logging:
  level:
    com.mall: debug
server:
  port: 88

