
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remote_user
    password: 139494tang
    url: jdbc:mysql://150.158.147.6:3306/mall_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  type-aliases-package: com.mall.coupon.entity
  global-config:
    db-config:
      id-type: auto
#  mapper-locations: classpath:/mapper/**/*.xml

server:
  port: 7000