spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remote_user
    password: 139494tang
    url: jdbc:mysql://150.158.147.6:3306/mall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#mybatis-plus:
  type-aliases-package: com.mall.stock.entity
#  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 10000
