spring:
  application:
    name: mall-third-party
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: remote_user
    password: 139494tang
    url: jdbc:mysql://150.158.147.6:3306/mall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  cloud:
    nacos:
      server-addr: 121.36.99.140:8848
  main:
    web-application-type: reactive
logging:
  level:
    com.mall: debug
server:
  port: 12000